faq/README.md

help in memory -> held in memory

typo in faq

---

.vuepress/theme/styles/theme.styl

fix(theme): fix headers margin/padding to fix anchors link issue

---

.vuepress/theme/Layout.vue

fix(os-detection): fix lifecycle loading and build

---

storyscript/README.md

The type checking section gets formatted pretty weirdly:

Improve the Storyscript documentation

---

package-lock.json
package.json

fixing #33 by adding `sitemap.xml` to the bundle

feat(sitemap): add sitemap generation after build

---

.vuepress/theme/AlgoliaSearchBox.vue
.vuepress/theme/Layout.vue
.vuepress/theme/Sidebar.vue
.vuepress/theme/styles/_code.scss
.vuepress/theme/styles/_content.scss
.vuepress/theme/styles/_sidebar.scss
.vuepress/theme/styles/theme.scss
storyscript/README.md

fix(app): fix layout

---

.vuepress/theme/styles/_content.scss

fix(tables)

---

storyscript/README.md

This is a first start at documenting what's allowed. Any suggestions are welcome!
The table doesn't look super-nice yet:
CC @judepereira

Start to document Storyscript's type system

---

.vuepress/components/Feature.vue
.vuepress/config.js
.vuepress/enhanceApp.js
.vuepress/theme/AlgoliaSearchBox.vue
.vuepress/theme/Layout.vue
.vuepress/theme/Sidebar.vue
.vuepress/theme/styles/theme.scss
README.md
package-lock.json
package.json

migrate from asyncy to storyscript docs

chore(migration)

---

quick-start/README.md

Update command for Mac install in quickstart guide

---

.vuepress/theme/Sidebar.vue
.vuepress/theme/styles/_sidebar.scss

improve submenu and make it working for mobiles

feat(submenu)

---

cli/README.md
quick-start/README.md

They also have the badge in black:

Add Snap Store badges

---

storyscript/execution/README.md

Supersedes https://github.com/storyscript/docs.storyscript.io/pull/71

Improve the description of a SS execution

---

storyscript/advanced/README.md

Improve storyscript/advanced

---

package.json
yarn.lock

**NEED TO BE MERGED BEFORE ANY OTHER PR**

feat(theme): upgrade theme version

---

faq/README.md
functions/README.md
quick-start/README.md
services/README.md
storyscript/advanced/README.md
storyscript/basic-types/README.md
storyscript/execution/README.md
storyscript/flow/README.md
storyscript/functions/README.md
storyscript/secrets/README.md
storyscript/services/README.md
storyscript/syntax/README.md

Currently just an alias to coffeescript, but will be replaced with the real syntax highlighter soon.

Markdown codeblocks: s/coffeescript/storyscript/g

---

faq/README.md
functions/README.md
quick-start/README.md
services/README.md
storyscript/advanced/README.md
storyscript/basic-types/README.md
storyscript/execution/README.md
storyscript/flow/README.md
storyscript/functions/README.md
storyscript/secrets/README.md
storyscript/services/README.md
storyscript/syntax/README.md

Reverts storyscript/docs.storyscript.io#93

Revert "Markdown codeblocks: s/coffeescript/storyscript/g"

---

storyscript/advanced/README.md
storyscript/basic-types/README.md
storyscript/execution/README.md
storyscript/flow/README.md
storyscript/functions/README.md
storyscript/syntax/README.md

Mostly trivial. See the individual commits for details

A few Storyscript updates

---

support/README.md

Follow-up to https://github.com/storyscript/docs.storyscript.io/pull/108

Mention the public Slack on the support page

---

storyscript/basic-types/README.md

See also: https://github.com/storyscript/storyscript/releases/tag/0.21.1

0.21.1: single quotes are allowed inside string templates

---

storyscript/advanced/README.md

Based on old and new SS changes (see e.g. https://github.com/storyscript/storyscript/pull/1102, https://github.com/storyscript/storyscript/pull/1101, https://github.com/storyscript/storyscript/pull/1098, https://github.com/storyscript/storyscript/pull/1097, ...)

Improve docs for exception handling + scope

---

quick-start/README.md

Fixing a minor branding spelling error. 

---

storyscript/advanced/README.md

Add information about arithmetic operators support in the language.

chore(operators): update assignment operation section

---

.github/README.md

https://github.com/storyscript/community/issues/3

Add Code of Conduct shield
